Added ability to list servers/nodes.
DimensionDataResearch/ansible-modules-extras pull request #13
Opened 2016-09-25 17:37 UTC by aimonb

Added ability to list servers/nodes.

2016-09-25 20:41 UTC, jr2730 commented
I don't see much GET support. Is get supposed to be different than list?
If not, maybe make get an alias for list?
If so, I don't see any GET support.

2016-09-25 21:11 UTC, relaxdiego commented
I can't think of a scenario when anyone would need a separate GET in this case. Ansible always works with a list of hosts even if the list only contains one host.

2016-09-25 21:23 UTC, aimonb commented
get is alias for list.


On 9/25/16 4:11 PM, Mark Maglana wrote:
>
> I can't think of a scenario when anyone would need a separate GET in
> this case. Ansible always works with a list of hosts even if the list
> only contains one host.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DimensionDataResearch/ansible-modules-extras/pull/13#issuecomment-249446960>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AADlp2_lmtjIrTx_LoAZOwGvAaETA7mvks5qtuN-gaJpZM4KF9Ku>.
>

2016-09-25 21:54 UTC, jr2730 commented
Might be better to use the AnsibleModule "alias" capability.
Cause right now you have 2 different "commands" that are both treated the same.
And it makes the documentation more confusing (UNLESS you somehow plan on separating the 2 commands at some point).

2016-09-25 22:29 UTC, aimonb commented
As far as I know alias only works for arguments, not their values.

2016-09-25 22:29 UTC, aimonb commented
I am thinking we just drop 'get'?

2016-09-25 22:36 UTC, aimonb commented
'get' has been removed.

2016-09-26 18:43 UTC, relaxdiego commented on cloud/dimensiondata/dimensiondata_compute.py
> +                             " is not list/get.")
you missed a spot ("list/get") :-)

2016-09-26 18:44 UTC, relaxdiego requested changes

2016-09-26 18:45 UTC, aimonb commented on cloud/dimensiondata/dimensiondata_compute.py
> +                             " is not list/get.")
doh! thanks!

2016-09-26 18:47 UTC, relaxdiego approved these changes

2016-09-26 18:48 UTC, merged